#!/bin/sh
# init-like orchestrator for prompt tuning
# Richard Jarry -- 2019 (Public Domain)

MODULE_DIR=$HOME"/.config/prompt/modules" # Module directory (script stash)
ACTIVE_DIR=$HOME"/.config/prompt/active"  # Active directory (script symlinks)

STARTING="["	# Change these if you want to change the visual
STOPPING="]"	# appearence of the enclosing for each module.

# Dump prompt chain if no args
if test "$#" -lt 1; then
	set -- "show"
fi

if test "$#" -gt 1; then
	echo "Too many arguments (expected 1 or less)"
	set -- "help"
fi

# Argument parser
case $1 in
    version|--version|-v)
    echo "Chain v0.1 alpha (April 2019)"
    ;;
    help|--help|-h)
    echo "Chain : System info display for your prompt."
    echo "Usage : $0 # For current chain display"
    echo "        $0 modules # To get a list of available info modules"
    echo "        $0 push:module1 # To put the module1 on your chain"
    echo "        $0 pop:module1  # To rid the module1 on your chain"
    echo "Chain uses this directory to store modules : $MODULE_DIR"
    echo "Chain uses this directory for active links : $ACTIVE_DIR"
    ;;
    active|list|ls|-l)
    ls $ACTIVE_DIR
    ;;  
    modules|mod|-m)
    ls $MODULE_DIR
    ;;  
    show|s|dump|-d)

        for module in $(ls $ACTIVE_DIR)
        do  
            CONTENTS=$(sh $MODULE_DIR/$module)

	    if test -n "$CONTENTS"; then
		echo -n $STARTING
		echo -n $CONTENTS
		echo -n $STOPPING
	    fi
        done
    ;;  
    push:*|++*)
    MODULE="${i#*:}"
    ln -s $MODULE_DIR/$MODULE $ACTIVE_DIR/
    ;;  
    pop:*|--*)
    MODULE="${i#*:}"
    echo $MODULE
    rm -i $ACTIVE_DIR/$MODULE
    ;;  
esac
